export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS';
export const FETCH_CLIENTS_FULFILLED = 'FETCH_CLIENTS_FULFILLED';
export const FETCH_CLIENTS_REJECTED = ' FETCH_CLIENTS_REJECTED';

export const EDIT_ROW_REQUEST = 'EDIT_ROW_REQUEST';
